uni_marca_anuncios:
    resource: "@uniMarcaBundle/Resources/config/routing/anuncios.yml"
    prefix:   /anuncios

uni_marca_comentarios:
    resource: "@uniMarcaBundle/Resources/config/routing/comentarios.yml"
    prefix:   /comentarios

uni_marca_categorias:
    resource: "@uniMarcaBundle/Resources/config/routing/categorias.yml"
    prefix:   /categorias

uni_marca_noticias:
    resource: "@uniMarcaBundle/Resources/config/routing/noticias.yml"
    prefix:   /noticias

uni_marca_homepage:
    path:     /hello/{name}
    defaults: { _controller: uniMarcaBundle:Default:index }
